import Head from "next/head";
export default function Home() {
    return (
        <div>
            <Head>
                <title>Port</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="">
                <section className="">
                    <h1>Hello</h1>
                </section>
            </main>
        </div>
    );
}
